engine:
  geometry:
    bore: 0.086          # m
    stroke: 0.086        # m
    con_rod: 0.1455      # m
    comp_ratio: 12.5     # -
    
  operating_conditions:
    speed: 2000          # rpm
    wall_temp: 400       # K
    
  simulation:
    start_ca: -180       # deg (IVC)
    end_ca: 180         # deg (EVO)

chemistry:
  mechanism: "mechanisms/Nissan_chem.yaml"  # Mechanism file path
  fuel: "C8H18"         # iso-octane
  phi: 0.7              # lean mixture
  egr: 0.3              # residual gas fraction
    
initial_conditions:
  # Initial state at IVC (start of compression)
  pressure: 1.0e5        # Initial pressure [Pa]
  temperature: 450       # Initial temperature [K]
    
solver:
  method: "LSODA"       # solver method
  rtol: 1.0e-4          # relative tolerance
  atol: 1.0e-6          # absolute tolerance
  max_step: 1.0e-3      # maximum step size
  first_step: 1.0e-6    # initial step size
  
output:
  save_path: "results/"  # Path relative to project root
  plot_format: "png"
  dpi: 300 